### register
POST https://seahorse-app-36ato.ondigitalocean.app/v1/auth/login
Content-Type: application/json

{ 
  "email":"johan,grobler@prelo.co.za",
  "password":"password"
}


### register
POST https://seahorse-app-36ato.ondigitalocean.app/v1/auth/register
Content-Type: application/json

{
  "first_name":"Johan",
  "last_name":"Grobler",
  "email":"johan,grobler@prelo.co.za",
  "password":"password"
}
